### ISSUE TITLE
WatchServiceTest is failing on Windows

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse-jkube/jkube#2968]
### Component

JKube Kit

### Description
_Originally posted by @Sintivrousai in [Gitter Thread](https://matrix.to/#/!QryyIuhARjRcebsrTd:gitter.im/$VDpQ2eEsvL4MwV0oUokloNBu1kOle8O3W8pb4rxD96E?via=gitter.im&via=matrix.org&via=jurr.org)_

It looks like WatchServiceTest is failing on Windows again. We had merged a fix https://github.com/eclipse-jkube/jkube/pull/2678 to fix this test but not sure why test has started failing again:

```
[ERROR] Failures:
[ERROR]   WatchServiceTest$Copy.callsPostExec:252
Expecting
  <CompletableFuture[Incomplete]>
to be completed within 5S.
```

### Expected Behavior
WatchServiceTest should pass on windows

### Acceptance Criteria
- [ ] WatchServiceTest should pass on windows

**Comment by Sintivrousai** [comment]
I'm a beginner but i would like to try resolve it.

**Comment by Sintivrousai** [comment]
Hello, as i was trying to see what's wrong with the test i noticed that sometimes it passed normally. I think maybe it has to do with if the docker desktop is open or not since the tests are for docker. If that's the case i could enable them only on linux or add this as a requirement?

**Comment by rohanKanojia** [comment]
@Sintivrousai : Could it be a timeout issue? Does test pass if you increase the timeout from 5 seconds to more?

**Comment by Sintivrousai** [comment]
That should be the case. I tried with 10sec and it passed.

**Comment by rohanKanojia** [comment]
@Sintivrousai : Hmm, I see. Does it pass everytime or it fails some time?

**Comment by Sintivrousai** [comment]
Not everytime apparently. I am testing with 20secs now and its okey so far. I am going to experiment it a little more.

**Comment by Sintivrousai** [comment]
I keep facing some problems and i have increased the time limits more than I expected (even to 3minutes). However, one good thing is that the fails has been reduced quite a bit. What i mean is that when i try to build it 2 times out of 3 it does not fail. I have changed the time empirically. It does not seem right to me to keep increasing the time.

**Comment by rohanKanojia** [comment]
@Sintivrousai : Maybe it's better to check what's causing wait in test execution and see if it's something related to windows. On Linux, the test passes normally

**Comment by l3002** [comment]
Hi @Sintivrousai , @rohanKanojia : I'm unable to replicate this issue. Are we sure that the test is still failing?

**Comment by vijaybhagwat24** [comment]
hi @rohanKanojia ,
took latest of master on local and ran the test cases:
![image](https://github.com/user-attachments/assets/0714d114-65e2-4ba1-ae58-53af30be0096)

test method "callsPostExec" mentioned is passed but other two test methods: 
1.buildImage()
2.customizesImage()
are failing. May be we can close this and open another issue for those.

**Comment by rohanKanojia** [comment]
It's not just on windows, this test is failing intermittently on MacOS as well:

```
Error:    WatchServiceTest$Build.buildsImage:144 
buildService.buildImage(
    org.eclipse.jkube.kit.config.image.ImageConfiguration@ae82ea04,
    null,
    org.eclipse.jkube.kit.common.JKubeConfiguration@99d014ba
);
Wanted 1 time:
-> at org.eclipse.jkube.kit.build.service.docker.BuildService.buildImage(BuildService.java:67)
But was 39 times:
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)



```
