### ISSUE TITLE
ci: MacOS compilation pipeline

### ISSUE THREAD

**Issue by manusa** [eclipse-jkube/jkube#3483]
I can see the jkube build successful on MacOS. Thanks a lot!

Maybe we can add a ci pipeline to make sure we don't break it in future.

However, sometimes I see an intermittent failure for [WatchServiceTest](https://github.com/eclipse-jkube/jkube/blob/master/jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/WatchServiceTest.java)

```
Error:    WatchServiceTest$Build.buildsImage:144 
buildService.buildImage(
    org.eclipse.jkube.kit.config.image.ImageConfiguration@ae82ea04,
    null,
    org.eclipse.jkube.kit.common.JKubeConfiguration@99d014ba
);
Wanted 1 time:
-> at org.eclipse.jkube.kit.build.service.docker.BuildService.buildImage(BuildService.java:67)
But was 39 times:
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
-> at org.eclipse.jkube.kit.build.service.docker.WatchService.lambda$createBuildWatchTask$1(WatchService.java:160)
```

Are you able to reproduce this issue on your machine?

_Originally posted by @rohanKanojia in https://github.com/eclipse-jkube/jkube/issues/3462#issuecomment-2428286837_

**Comment by rohanKanojia** [comment]
It's also possible to add a pipeline for windows (at the moment only gradle-plugin/it module is failing). We cane exclude that module for now and test rest of the modules.

**Comment by manusa** [comment]
That should be tracked in a separate issue.

**Comment by manusa** [comment]
Getting this:
```
Error:  Errors: 
Error:    WatchServiceTest$Copy.callsPostExec » IO Failed to delete temp directory /var/folders/q5/6nls1_g145s2fl1lbvx2zby40000gn/T/junit15225183195109158703. The following paths could not be deleted (see suppressed exceptions for details): <root>, target, target/test-app, target/test-app/tmp
```

**Comment by manusa** [comment]
Likely related to: https://github.com/junit-team/junit5/issues/2811

I'll try to fix the test.
